// The wire contract between the chat tab and the relay that runs Claude on the
// remote host.
//
// The relay (resources/relay/relay.ts) is a small Node process the app uploads
// and starts inside tmux. It drives Claude Code through the Agent SDK and talks
// to the app through two append-only files in its chat directory:
//
//   ~/.claude-ssh-manager/chats/<chatId>/
//     config.json    written once by the app before start (ChatConfig)
//     state.json     rewritten by the relay (ChatState) — for listing and restart
//     events.jsonl   relay -> app, one ChatEvent per line
//     inbox.jsonl    app -> relay, one ChatCommand per line
//
// Files rather than a socket so nothing is lost while the laptop sleeps: the
// relay keeps writing, and the app picks up from the last byte offset it saw.
// Offsets are always bytes — the stream is UTF-8 and mostly not ASCII.
//
// Shapes of the SDK messages behind these events were confirmed against the
// server's Claude Code 2.1.289 / @anthropic-ai/claude-agent-sdk 0.3.289.

/** Root of all chat state on the remote, relative to $HOME. */
export const CHAT_ROOT = '.claude-ssh-manager'
export const CHAT_DIR = `${CHAT_ROOT}/chats`
/** Reported by the relay in its `ready` event. On the host the file is named by a hash of its content. */
export const RELAY_VERSION = 1
/** tmux session the relay of one chat runs in. */
export const chatTmuxSession = (chatId: string): string => `chat-${chatId}`
/** Chat ids are generated by the app: `c` + 12 hex chars. Anything else is refused. */
export const CHAT_ID_RE = /^c[0-9a-f]{12}$/

/**
 * Permission mode as the user picks it. `bypass` is not the SDK's
 * bypassPermissions: in that SDK mode canUseTool is never called, so
 * AskUserQuestion and ExitPlanMode could not reach the UI. The relay runs the
 * SDK in `default` and allows every tool itself, except those two.
 */
export type ChatMode = 'bypass' | 'default' | 'acceptEdits' | 'plan'

export interface ChatImage {
  /** e.g. image/png, image/jpeg, image/gif, image/webp */
  mediaType: string
  /** base64, no data: prefix */
  data: string
}

/** Written by the app to config.json before the relay starts. */
export interface ChatConfig {
  chatId: string
  /** Absolute working directory on the remote. */
  cwd: string
  /** Model alias or id (`opus`, `sonnet`, `claude-haiku-4-5`…); absent = Claude Code's default. */
  model?: string
  mode: ChatMode
  /** Absolute path of the real claude binary (never the user's bash wrapper function). */
  claudePath: string
  /** Resume this Claude session id instead of starting fresh. */
  resume?: string
  /** Short label for lists; the first prompt if absent. */
  title?: string
  createdAt: number
}

/** Rewritten by the relay on every change worth listing. */
export interface ChatState {
  chatId: string
  pid: number
  sessionId?: string
  cwd: string
  model?: string
  mode: ChatMode
  title?: string
  /** running = a turn is in progress; waiting = a request is open for the user. */
  status: 'starting' | 'idle' | 'running' | 'waiting' | 'exited'
  /** Bytes of inbox.jsonl already consumed, so a restarted relay doesn't replay commands. */
  inboxOffset: number
  /** Last seq written to events.jsonl. */
  seq: number
  updatedAt: number
}

// ---- events: relay -> app ----

/** A content block as the chat renders it (the SDK's, minus signatures). */
export type ChatBlock =
  | { type: 'text'; text: string }
  | { type: 'thinking'; text: string }
  | { type: 'tool_use'; id: string; name: string; input: unknown }

export interface SlashCommandInfo {
  name: string
  description: string
  argumentHint?: string
}

export interface ModelChoice {
  /** What set_model takes: `default`, `opus`, `sonnet`, a full id… */
  value: string
  displayName: string
  description?: string
}

export interface RateLimitInfo {
  status: string
  rateLimitType?: string
  resetsAt?: number
  /** Window name -> 0..1 utilization, e.g. five_hour, seven_day. */
  windows?: Record<string, { utilization: number; resetsAt?: number }>
}

export type ChatEventBody =
  /** Relay process started (also after a restart). */
  | { t: 'ready'; pid: number; relayVersion: number }
  /** Session is up. Also re-sent when commands or the model list change. */
  | {
      t: 'init'
      sessionId: string
      model: string
      cwd: string
      mode: ChatMode
      slashCommands: SlashCommandInfo[]
      models: ModelChoice[]
    }
  /** Previous conversation of a resumed session, oldest first. */
  | { t: 'history'; messages: ChatHistoryMessage[] }
  /** The user's message, echoed when the relay hands it to Claude. */
  | { t: 'user'; id: string; text: string; images?: ChatImage[] }
  /** A content block began streaming. */
  | { t: 'block_start'; msgId: string; index: number; kind: 'text' | 'thinking' | 'tool_use'; toolName?: string; toolId?: string; parentToolUseId?: string | null }
  /** Streamed text, coalesced (~50 ms). Thinking deltas carry no text in this Claude Code build; they still mark activity. */
  | { t: 'delta'; msgId: string; index: number; kind: 'text' | 'thinking'; text: string }
  /** A complete assistant message — authoritative over any deltas for the same msgId+index. */
  | { t: 'assistant'; msgId: string; blocks: ChatBlock[]; parentToolUseId: string | null }
  /** Output of a tool call. `content` is capped at 20 000 chars. */
  | { t: 'tool_result'; toolUseId: string; content: string; isError: boolean; parentToolUseId: string | null; truncated?: boolean }
  | { t: 'status'; status: ChatState['status'] }
  | { t: 'mode'; mode: ChatMode }
  | { t: 'model'; model: string }
  /**
   * Claude needs the user. `question` = AskUserQuestion (input.questions),
   * `plan` = ExitPlanMode (input.plan markdown), `permission` = any other tool
   * while the mode is not bypass.
   */
  | { t: 'request'; reqId: string; kind: 'permission' | 'question' | 'plan'; toolName: string; toolUseId?: string; input: unknown; title?: string; description?: string }
  /** A request is settled — by the user, or cancelled by an interrupt. */
  | { t: 'request_done'; reqId: string; outcome: 'allow' | 'deny' | 'cancelled' }
  /** End of a turn. */
  | { t: 'result'; isError: boolean; subtype: string; costUsd: number; durationMs?: number; numTurns?: number; text?: string; contextWindow?: number; inputTokens?: number }
  | { t: 'rate_limit'; info: RateLimitInfo }
  /** Context was compacted (automatically or by /compact). */
  | { t: 'compact'; trigger: 'manual' | 'auto'; preTokens?: number }
  /** Something went wrong that is not part of a turn's result. */
  | { t: 'error'; message: string }
  /** Relay is exiting (stop command, fatal error). */
  | { t: 'exit'; reason: string }

export type ChatEvent = ChatEventBody & { seq: number; ts: number }

/** One message of a resumed session's earlier conversation. */
export type ChatHistoryMessage =
  | { role: 'user'; text: string }
  | { role: 'assistant'; blocks: ChatBlock[] }
  | { role: 'tool_result'; toolUseId: string; content: string; isError: boolean }

// ---- commands: app -> relay ----

export type ChatCommandBody =
  | { t: 'user'; text: string; images?: ChatImage[] }
  | { t: 'interrupt' }
  | { t: 'set_model'; model: string }
  | { t: 'set_mode'; mode: ChatMode }
  /**
   * Settle a request. For a question, `updatedInput` is
   * `{ questions, answers: { [questionText]: label | 'a, b' | freeText } }`.
   * For a plan, `allow` approves; `deny` + `message` keeps planning with feedback.
   */
  | { t: 'answer'; reqId: string; decision: 'allow' | 'deny'; updatedInput?: unknown; message?: string }
  /** End the session and exit the relay. */
  | { t: 'stop' }

/** `id` is unique per command (the app's), used to echo user messages. */
export type ChatCommand = ChatCommandBody & { id: string }

// ---- IPC: renderer <-> main (window.api.chat*) ----

export interface ChatSummary {
  chatId: string
  config: ChatConfig
  state: ChatState | null
  /** The relay's tmux session exists. */
  alive: boolean
  /** events.jsonl size in bytes. */
  size: number
}

export interface ChatStartArgs {
  connectionId: string
  password?: string
  cwd: string
  model?: string
  mode: ChatMode
  resume?: string
  title?: string
}

/** A batch of whole event lines from a live stream; `next` is the byte offset after them. */
export interface ChatStreamData {
  streamId: string
  events: ChatEvent[]
  next: number
}

export interface ChatStreamEnd {
  streamId: string
  /** Absent on a clean close (unstream). */
  error?: string
}
